# Generated by Django 5.1.1 on 2024-10-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contributions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funeral_kitty', models.IntegerField()),
                ('monthly_contributions', models.IntegerField()),
                ('expenditure', models.IntegerField()),
                ('savings', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='contributions',
            options={'verbose_name_plural': 'Contributions'},
        ),
        migrations.AddField(
            model_name='contributions',
            name='savings',
            field=models.IntegerField(default=0),
        ),
    ]
