# Generated by Django 5.1.1 on 2024-10-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_overallcontribution_alter_contributions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='profiles/'),
        ),
    ]
