# Generated by Django 5.1.1 on 2024-10-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_customuser_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='profile_picture',
        ),
    ]
