# Generated by Django 5.1.1 on 2024-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_memberdependent_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdependent',
            name='image',
            field=models.ImageField(default='', upload_to='dependents/'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile',
            field=models.ImageField(default='', upload_to='profiles/'),
        ),
    ]
