# Generated by Django 5.1.1 on 2024-09-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_memberdependent_image_memberprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdependent',
            old_name='image',
            new_name='proof',
        ),
        migrations.AddField(
            model_name='memberdependent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
